platform :ios,'7.0'
target 'Tuke' do

 pod 'MBProgressHUD', '0.9.2'
 pod 'AFNetworking', '~> 3.1.0'
 pod 'SDWebImage', '3.7.4'
 pod 'JSONModel', '1.2.0'
 pod 'Masonry', '0.6.4'
 pod 'Qiniu', '~> 7.1'
 pod 'MJExtension','~>3.0.13'
 pod 'TTTAttributedLabel', '1.13.4'
 pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5' # 无 idfa版本
 pod 'SFPSDWriter', '0.3.1'
 pod 'MGSwipeTableCell', '~> 1.6.1' # 侧滑三方

end
